import os
import requests
import urllib.parse
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required, current_user
from models import db, User, LoginHistory, AlertSettings

bp = Blueprint('auth', __name__, url_prefix='/auth')

USER_ROLES = [
    ('owner', 'Owner / Plant Head'),
    ('admin', 'Administrator'),
    ('operator', 'Machine / Gate Operator'),
    ('accountant', 'Accountant / Billing'),
    ('supervisor', 'Plant Supervisor'),
    ('staff', 'General Staff')
]


def _dispatch_email_alert(subject, body_text, to_email):
    """Dispatches real-time email notification using SMTP."""
    if not to_email:
        to_email = 'nishanthissan1515@gmail.com'

    settings = AlertSettings.query.first()
    smtp_host = settings.smtp_host if (settings and settings.smtp_host) else 'smtp.gmail.com'
    smtp_port = settings.smtp_port if (settings and settings.smtp_port) else 587
    smtp_user = settings.smtp_user if (settings and settings.smtp_user) else ''
    smtp_pass = settings.smtp_password if (settings and settings.smtp_password) else ''

    # If custom SMTP credentials are provided, send via SMTP server
    if smtp_user and smtp_pass:
        try:
            msg = MIMEMultipart('alternative')
            msg['Subject'] = subject
            msg['From'] = f"FlyAsh Alert <{smtp_user}>"
            msg['To'] = to_email

            html_content = f"""
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 8px; background-color: #ffffff;">
                <div style="background-color: #1e3a8a; padding: 15px; border-radius: 6px; text-align: center; color: #ffffff;">
                    <h2 style="margin: 0; font-size: 20px;">FlyAsh & Block Plant Management</h2>
                    <p style="margin: 4px 0 0 0; font-size: 13px; opacity: 0.9;">Security & Login Alert System</p>
                </div>
                <div style="padding: 20px 0; color: #334155; line-height: 1.6;">
                    <p style="font-size: 15px; font-weight: bold; color: #0f172a;">{subject}</p>
                    <div style="background-color: #f8fafc; border-left: 4px solid #3b82f6; padding: 15px; border-radius: 4px; margin: 15px 0;">
                        <pre style="font-family: inherit; margin: 0; white-space: pre-wrap; font-size: 14px;">{body_text}</pre>
                    </div>
                    <p style="font-size: 13px; color: #64748b; margin-top: 20px;">
                        This automated notification was generated by your FlyAsh Manager system running on your local server.
                    </p>
                </div>
            </div>
            """

            msg.attach(MIMEText(body_text, 'plain'))
            msg.attach(MIMEText(html_content, 'html'))

            with smtplib.SMTP(smtp_host, smtp_port, timeout=8) as server:
                server.starttls()
                server.login(smtp_user, smtp_pass)
                server.sendmail(smtp_user, [to_email], msg.as_string())
            print(f"[OK] Email alert successfully sent to {to_email}")
            return True, "Email sent successfully via SMTP!"
        except Exception as e:
            print(f"[WARN] SMTP Email delivery error: {e}")
            return False, f"SMTP Error: {str(e)}"
    
    # Fallback log notice when SMTP credentials are not configured yet
    print(f"[INFO] Email alert prepared for {to_email}")
    return True, f"Email notification queued for {to_email}. (Enter your Gmail App Password under Advanced SMTP to send live emails)"


def _dispatch_mobile_alert(message_text):
    """Dispatches real-time alert message to owner's mobile phone (WhatsApp/Telegram/SMS/Webhook)."""
    try:
        settings = AlertSettings.query.first()
        if not settings or not settings.is_enabled:
            return

        raw_phone = (settings.phone_number or '8072416903').replace('+', '').replace(' ', '').replace('-', '').strip()
        phone = ('91' + raw_phone) if len(raw_phone) == 10 else raw_phone

        if settings.channel in ['whatsapp', 'both'] and phone and settings.api_key:
            text_encoded = urllib.parse.quote(message_text)
            url = f"https://api.callmebot.com/whatsapp.php?phone={phone}&text={text_encoded}&apikey={settings.api_key}"
            requests.get(url, timeout=4)

        if settings.channel in ['telegram', 'both'] and settings.api_key and settings.chat_id:
            url = f"https://api.telegram.org/bot{settings.api_key}/sendMessage"
            payload = {'chat_id': settings.chat_id, 'text': message_text}
            requests.post(url, json=payload, timeout=4)

        if settings.channel == 'sms' and phone and settings.api_key:
            url = "https://www.fast2sms.com/dev/bulkV2"
            headers = {'authorization': settings.api_key}
            payload = {
                'route': 'q',
                'message': message_text,
                'language': 'english',
                'flash': 0,
                'numbers': raw_phone
            }
            requests.post(url, headers=headers, json=payload, timeout=4)

        if settings.channel == 'webhook' and settings.webhook_url:
            requests.post(settings.webhook_url, json={'phone': phone, 'alert': message_text, 'timestamp': datetime.now().isoformat()}, timeout=4)

    except Exception as e:
        print(f"[WARN] Error dispatching mobile alert: {e}")


def _send_login_alert(user, login_identifier, status, ip_address, user_agent):
    """Logs sign-in event, prints to console, and sends mobile + email alert to owner about the login user."""
    try:
        uname = user.username if user else (login_identifier or 'UNKNOWN')
        uemail = user.email if user else (login_identifier if '@' in (login_identifier or '') else '')
        urole = user.role if user else 'guest'
        uid = user.id if user else None

        log_entry = LoginHistory(
            user_id=uid,
            username=uname,
            email=uemail,
            user_role=urole,
            ip_address=ip_address,
            user_agent=user_agent[:250] if user_agent else '',
            status=status,
            timestamp=datetime.now()
        )
        db.session.add(log_entry)
        db.session.commit()

        time_str = datetime.now().strftime('%d-%b-%Y at %I:%M:%S %p')
        print(f"\n{'='*60}\n  [LOGIN ALERT] User: '{uname}' ({uemail}) | Role: {urole}\n  Status: {status} | Time: {time_str} | IP: {ip_address}\n{'='*60}\n")

        settings = AlertSettings.query.first()
        owner_email = settings.owner_email if (settings and settings.owner_email) else 'nishanthissan1515@gmail.com'

        # Construct alert content
        if status == 'SUCCESS':
            if user and (user.role == 'owner' or user.email == owner_email):
                subject = f"🔔 FlyAsh Manager: Owner Login Alert ({user.name or uname})"
                body = (f"Owner Sign-in Notification:\n\n"
                        f"• Account: {user.name or uname} ({uemail})\n"
                        f"• Role: {urole.capitalize()}\n"
                        f"• Time: {time_str}\n"
                        f"• IP Address: {ip_address}\n"
                        f"• Device: {user_agent or 'Standard Browser'}")
            else:
                display_name = user.name or user.username if user else uname
                subject = f"🚨 FlyAsh Manager: Staff Login Alert - {display_name} ({urole.capitalize()})"
                body = (f"Alert: A user / staff member has just logged in to your plant system:\n\n"
                        f"• User Name: {display_name}\n"
                        f"• Login Email: {uemail or uname}\n"
                        f"• Role / Permission: {urole.capitalize()}\n"
                        f"• Time of Login: {time_str}\n"
                        f"• IP Address: {ip_address}\n"
                        f"• Device / Browser: {user_agent or 'Standard Browser'}")
        elif status == 'WRONG_PASSWORD' and user:
            display_name = user.name or user.username
            subject = f"🚨 Security Alert: WRONG PASSWORD Attempt for '{display_name}'"
            body = (f"⚠️ SECURITY WARNING - WRONG PASSWORD ENTERED\n\n"
                    f"Someone attempted to log in with an INCORRECT PASSWORD to:\n"
                    f"• Target Account: {display_name} ({user.email or user.username})\n"
                    f"• Role / Permission: {urole.capitalize()}\n"
                    f"• Time of Attempt: {time_str}\n"
                    f"• IP Address: {ip_address}\n"
                    f"• Device / Browser: {user_agent or 'Standard Browser'}\n\n"
                    f"Notification dispatched to Owner ({owner_email} & 8072416903).")
        else:
            subject = f"⚠️ Security Alert: Failed Login Attempt ({login_identifier})"
            body = (f"⚠️ SECURITY WARNING - FAILED LOGIN ATTEMPT\n\n"
                    f"An unknown or failed login attempt was detected on your system:\n"
                    f"• Attempted Login ID: {login_identifier}\n"
                    f"• Time of Attempt: {time_str}\n"
                    f"• IP Address: {ip_address}\n"
                    f"• Device / Browser: {user_agent or 'Standard Browser'}\n\n"
                    f"Notification dispatched to Owner ({owner_email} & 8072416903).")

        # 1. Dispatch Mobile Bot / WhatsApp / SMS to 8072416903
        _dispatch_mobile_alert(body)

        # 2. Dispatch Direct Email to nishanthissan1515@gmail.com
        if settings is None or settings.email_alerts_enabled:
            _dispatch_email_alert(subject, body, owner_email)

    except Exception as e:
        db.session.rollback()
        print(f"[WARN] Error in _send_login_alert: {e}")


# ==============================================================================
# AUTHENTICATION ROUTES
# ==============================================================================

@bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('dashboard.index'))
    
    if request.method == 'POST':
        login_input = (request.form.get('email') or request.form.get('username') or '').strip()
        password = request.form.get('password')
        ip_addr = request.remote_addr or '127.0.0.1'
        u_agent = request.headers.get('User-Agent', '')
        
        if not login_input:
            flash('Please enter your username or email.', 'error')
            return render_template('login.html')

        # Find user by Email (case-insensitive) or Username
        user = User.query.filter(
            (db.func.lower(User.email) == login_input.lower()) | 
            (db.func.lower(User.username) == login_input.lower())
        ).first()
        
        if user:
            if hasattr(user, 'is_active') and not user.is_active:
                flash('Your account has been deactivated. Please contact the administrator.', 'error')
                _send_login_alert(user, login_input, 'DEACTIVATED', ip_addr, u_agent)
                return render_template('login.html')

            if user.check_password(password):
                login_user(user)
                _send_login_alert(user, login_input, 'SUCCESS', ip_addr, u_agent)
                
                user_display = user.name or user.username
                flash(f'Welcome back, {user_display}!', 'success')
                return redirect(url_for('dashboard.index'))
            else:
                # WRONG PASSWORD for existing user account
                _send_login_alert(user, login_input, 'WRONG_PASSWORD', ip_addr, u_agent)
                flash('Invalid username or password.', 'error')
        else:
            # User not found in database
            _send_login_alert(None, login_input, 'USER_NOT_FOUND', ip_addr, u_agent)
            flash('Invalid username or password.', 'error')
            
    return render_template('login.html')


@bp.route('/logout')
@login_required
def logout():
    uname = current_user.name or current_user.username
    logout_user()
    flash(f'You have been signed out successfully.', 'info')
    return redirect(url_for('auth.login'))


# ==============================================================================
# USER / STAFF MANAGEMENT & PROFILE
# ==============================================================================

@bp.route('/users')
@login_required
def users_list():
    """List all application users / staff accounts."""
    users = User.query.order_by(User.role, User.username).all()
    return render_template('auth/users_list.html', users=users, roles=dict(USER_ROLES))


@bp.route('/users/add', methods=['GET', 'POST'])
@login_required
def user_add():
    """Add a new staff / user account."""
    if request.method == 'POST':
        name = request.form.get('name', '').strip()
        email = request.form.get('email', '').strip().lower()
        username = request.form.get('username', '').strip().lower()
        password = request.form.get('password', '').strip()
        role = request.form.get('role', 'staff')
        phone = request.form.get('phone', '').strip()
        is_active = request.form.get('is_active') == 'on'

        if not email:
            flash('Email address is required.', 'error')
            return render_template('auth/user_form.html', roles=USER_ROLES, user=None)

        if not username:
            username = email.split('@')[0]

        if not password or len(password) < 4:
            flash('Password must be at least 4 characters long.', 'error')
            return render_template('auth/user_form.html', roles=USER_ROLES, user=None)

        # Check for duplicates
        existing_email = User.query.filter(db.func.lower(User.email) == email).first()
        if existing_email:
            flash(f'User with email "{email}" already exists.', 'error')
            return render_template('auth/user_form.html', roles=USER_ROLES, user=None)

        existing_user = User.query.filter(db.func.lower(User.username) == username).first()
        if existing_user:
            flash(f'Username "{username}" is already taken. Please choose another username.', 'error')
            return render_template('auth/user_form.html', roles=USER_ROLES, user=None)

        try:
            new_user = User(
                name=name or username,
                email=email,
                username=username,
                role=role,
                phone=phone,
                is_active=is_active
            )
            new_user.set_password(password)
            db.session.add(new_user)
            db.session.commit()
            flash(f'Staff account "{new_user.name}" (@{new_user.username}) created successfully! They can now log in with username "{new_user.username}" or email "{new_user.email}".', 'success')
            return redirect(url_for('auth.users_list'))
        except Exception as e:
            db.session.rollback()
            flash(f'Error creating user: {str(e)}', 'error')

    return render_template('auth/user_form.html', roles=USER_ROLES, user=None)


@bp.route('/users/<int:id>/edit', methods=['GET', 'POST'])
@login_required
def user_edit(id):
    """Edit user / staff account."""
    user = User.query.get_or_404(id)
    
    if request.method == 'POST':
        name = request.form.get('name', '').strip()
        username = request.form.get('username', '').strip().lower()
        email = request.form.get('email', '').strip().lower()
        role = request.form.get('role', user.role)
        phone = request.form.get('phone', '').strip()
        new_password = request.form.get('new_password', '').strip()
        is_active = request.form.get('is_active') == 'on'

        if not email:
            flash('Email address cannot be empty.', 'error')
            return render_template('auth/user_form.html', roles=USER_ROLES, user=user)

        if not username:
            username = email.split('@')[0]

        # Check if email taken by another user
        conflict_email = User.query.filter(db.func.lower(User.email) == email, User.id != user.id).first()
        if conflict_email:
            flash(f'Email "{email}" is already used by another user.', 'error')
            return render_template('auth/user_form.html', roles=USER_ROLES, user=user)

        # Check if username taken by another user
        conflict_user = User.query.filter(db.func.lower(User.username) == username, User.id != user.id).first()
        if conflict_user:
            flash(f'Username "{username}" is already used by another user.', 'error')
            return render_template('auth/user_form.html', roles=USER_ROLES, user=user)

        try:
            user.name = name or user.name
            user.username = username
            user.email = email
            user.role = role
            user.phone = phone
            # Prevent deactivating yourself
            if user.id == current_user.id:
                user.is_active = True
            else:
                user.is_active = is_active

            if new_password:
                if len(new_password) < 4:
                    flash('New password must be at least 4 characters long.', 'error')
                    return render_template('auth/user_form.html', roles=USER_ROLES, user=user)
                user.set_password(new_password)

            db.session.commit()
            flash(f'User "{user.name}" (@{user.username}) updated successfully. New credentials are now active on all devices.', 'success')
            return redirect(url_for('auth.users_list'))
        except Exception as e:
            db.session.rollback()
            flash(f'Error updating user: {str(e)}', 'error')

    return render_template('auth/user_form.html', roles=USER_ROLES, user=user)


@bp.route('/users/<int:id>/delete', methods=['POST'])
@login_required
def user_delete(id):
    """Delete a user account."""
    if id == current_user.id:
        flash('You cannot delete your own account while signed in.', 'error')
        return redirect(url_for('auth.users_list'))
        
    user = User.query.get_or_404(id)
    try:
        name = user.name or user.username
        db.session.delete(user)
        db.session.commit()
        flash(f'User "{name}" deleted successfully.', 'success')
    except Exception as e:
        db.session.rollback()
        flash(f'Error deleting user: {str(e)}', 'error')
    return redirect(url_for('auth.users_list'))


@bp.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    """Update own profile (Name, Username, Email, Phone, and Password)."""
    user = current_user
    if request.method == 'POST':
        name = request.form.get('name', '').strip()
        username = request.form.get('username', '').strip().lower()
        email = request.form.get('email', '').strip().lower()
        phone = request.form.get('phone', '').strip()
        old_password = request.form.get('old_password', '').strip()
        new_password = request.form.get('new_password', '').strip()
        confirm_password = request.form.get('confirm_password', '').strip()

        if not email:
            flash('Email address is required.', 'error')
            return render_template('auth/profile.html')

        if not username:
            username = email.split('@')[0]

        # Check unique email
        conflict_email = User.query.filter(db.func.lower(User.email) == email, User.id != user.id).first()
        if conflict_email:
            flash(f'Email "{email}" is already used by another user.', 'error')
            return render_template('auth/profile.html')

        # Check unique username
        conflict_user = User.query.filter(db.func.lower(User.username) == username, User.id != user.id).first()
        if conflict_user:
            flash(f'Username "{username}" is already taken by another account.', 'error')
            return render_template('auth/profile.html')

        password_changed = False
        if new_password:
            if not old_password:
                flash('Please enter your current password to set a new password.', 'error')
                return render_template('auth/profile.html')
            if not user.check_password(old_password):
                flash('Incorrect current password.', 'error')
                return render_template('auth/profile.html')
            if len(new_password) < 4:
                flash('New password must be at least 4 characters long.', 'error')
                return render_template('auth/profile.html')
            if new_password != confirm_password:
                flash('New password and confirmation do not match.', 'error')
                return render_template('auth/profile.html')
            user.set_password(new_password)
            password_changed = True

        try:
            user.name = name or user.name
            user.username = username
            user.email = email
            user.phone = phone
            db.session.commit()

            # Also update owner email in alert settings if owner
            settings = AlertSettings.query.first()
            if settings and user.role in ['owner', 'admin']:
                settings.owner_email = email
                settings.owner_name = name or settings.owner_name
                if phone:
                    settings.phone_number = phone
                db.session.commit()

            # Security notification
            time_str = datetime.now().strftime('%d-%b-%Y at %I:%M %p')
            msg_details = []
            if password_changed:
                msg_details.append("Password updated")
            msg_details.append(f"Username: {username}")
            msg_details.append(f"Email: {email}")

            sec_msg = f"🔐 Security Notice: Account profile for '{user.name or username}' was updated on {time_str}.\nChanges: {', '.join(msg_details)}.\nYou can now log in across all devices with your new credentials."
            _dispatch_mobile_alert(sec_msg)
            _dispatch_email_alert("🔐 FlyAsh Manager: Profile & Password Updated", sec_msg, email)

            flash(f'Profile updated successfully! You can now sign in using username "{username}" or email "{email}" on any device with your new password.', 'success')
            return redirect(url_for('dashboard.index'))
        except Exception as e:
            db.session.rollback()
            flash(f'Error updating profile: {str(e)}', 'error')

    return render_template('auth/profile.html')


@bp.route('/history')
@login_required
def login_history():
    """Security audit log of all sign-ins."""
    history = LoginHistory.query.order_by(LoginHistory.timestamp.desc()).limit(100).all()
    return render_template('auth/login_history.html', history=history)


@bp.route('/change-password', methods=['GET', 'POST'])
@login_required
def change_password():
    """Owner, Admin & Staff password update."""
    if request.method == 'POST':
        old_password = request.form.get('old_password')
        new_password = request.form.get('new_password')
        confirm_password = request.form.get('confirm_password')
        
        if not current_user.check_password(old_password):
            flash('Incorrect current password.', 'error')
        elif not new_password or len(new_password) < 4:
            flash('New password must be at least 4 characters long.', 'error')
        elif new_password != confirm_password:
            flash('New password and confirmation do not match.', 'error')
        else:
            current_user.set_password(new_password)
            db.session.commit()
            flash('Password updated successfully! Your updated password is saved in the database and active across all devices immediately.', 'success')
            
            # Send alert about password change
            time_str = datetime.now().strftime('%d-%b-%Y at %I:%M %p')
            msg = f"🔐 Security Notice: Password for user '{current_user.name or current_user.username}' was changed on {time_str}."
            _dispatch_mobile_alert(msg)
            _dispatch_email_alert("🔐 FlyAsh Manager: Password Changed Alert", msg, current_user.email or 'nishanthissan1515@gmail.com')
            return redirect(url_for('dashboard.index'))
            
    return render_template('auth/change_password.html')


@bp.route('/alert-settings', methods=['GET', 'POST'])
@login_required
def alert_settings():
    """Configure mobile phone and email notifications for logins and security alerts."""
    settings = AlertSettings.query.first()
    if not settings:
        settings = AlertSettings(
            owner_name='Nishanth (Owner)',
            owner_email='nishanthissan1515@gmail.com',
            email_alerts_enabled=True,
            is_enabled=True
        )
        db.session.add(settings)
        db.session.commit()

    if request.method == 'POST':
        action = request.form.get('action')

        if action == 'test_mobile':
            # Send test alert to owner's phone
            test_msg = f"✅ Test Alert: Mobile notifications are successfully connected to your FlyAsh Manager at {datetime.now().strftime('%I:%M %p, %d-%b-%Y')}!"
            _dispatch_mobile_alert(test_msg)
            flash('Test mobile alert dispatched! Please check your mobile phone.', 'info')

        elif action == 'test_email':
            # Send test email to owner's email
            target_email = request.form.get('owner_email', '').strip() or settings.owner_email or 'nishanthissan1515@gmail.com'
            success, msg_res = _dispatch_email_alert(
                "✅ Test Email: FlyAsh Manager Alert Connected",
                f"Hello Nishanth,\n\nThis is a test notification confirming that email alerts are connected to {target_email} at {datetime.now().strftime('%I:%M %p, %d-%b-%Y')}.\n\nYou will receive instant notifications whenever any user logs into your FlyAsh plant system!",
                target_email
            )
            flash(f'Email test completed for {target_email}: {msg_res}', 'info' if success else 'warning')

        else:
            # Save alert settings
            settings.is_enabled = request.form.get('is_enabled') == 'on'
            settings.email_alerts_enabled = request.form.get('email_alerts_enabled') == 'on'
            settings.channel = request.form.get('channel', 'whatsapp')
            settings.phone_number = request.form.get('phone_number', '').strip()
            settings.owner_name = request.form.get('owner_name', 'Nishanth (Owner)').strip()
            settings.owner_email = request.form.get('owner_email', 'nishanthissan1515@gmail.com').strip()
            settings.smtp_host = request.form.get('smtp_host', 'smtp.gmail.com').strip()
            settings.smtp_port = int(request.form.get('smtp_port', 587) or 587)
            settings.smtp_user = request.form.get('smtp_user', '').strip()
            settings.smtp_password = request.form.get('smtp_password', '').strip()
            settings.api_key = request.form.get('api_key', '').strip()
            settings.chat_id = request.form.get('chat_id', '').strip()
            settings.webhook_url = request.form.get('webhook_url', '').strip()
            settings.alert_on_all_users = request.form.get('alert_on_all_users') == 'on'

            db.session.commit()
            flash('Owner mobile and email alert settings saved successfully!', 'success')

    return render_template('auth/alert_settings.html', settings=settings)
